#!/bin/bash
git config --global user.name "Apon77"
git config --global user.email "khalakuzzamanapon5@gmail.com"
git config --global core.editor vim
git config --global credential.helper store
echo "https://apon77:$password@github.com" > ~/.git-credentials
