on: 
  schedule:
    - cron: '10 18 10,15 * *'
  push:

jobs:
  job1:
    name: auto push
    runs-on: ubuntu-latest
    env:
      password: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: git config
      run: |
        ./config.sh
    - name: test
      run: |
        ./test.sh
