name: auto-trigger-push
#on:
#  schedule:
#    - cron: '0 19 * * 1,3,5'
#  push:

jobs:
  job1:
    name: auto push
    runs-on: ubuntu-latest
    env:
      password: ${{ secrets.PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: git config
      run: |
        ./config.sh
    - name: push
      run: |
        ./push.sh
